#define default_gain 100
#define totalGain default_gain
#define constantGain default_gain
#define rampGain default_gain
#define squareGain default_gain
#define sineGain default_gain
#define triangleGain default_gain
#define sawtoothdownGain default_gain
#define sawtoothupGain default_gain
#define springGain default_gain
#define damperGain default_gain
#define inertiaGain default_gain
#define frictionGain default_gain
