name=Joystick
version=1.0.0
author=JMRiego <jmriego@telefonica.net>
maintainer=JMRiego <jmriego@telefonica.net>
sentence=A library that makes coding a Joystick a breeze.
paragraph=Supports FFB multi axis
category=Communication
url=http://example.com/
architectures=avr
includes=Joystick.h
